name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Start SUT and run tests
        run: |
          # Запускаем сервер в фоне
          java -jar ./artifacts/app-mbank.jar &
          SERVER_PID=$!
          echo "Server started with PID: $SERVER_PID"
          
          # Даем серверу время на запуск
          echo "Waiting for server to start..."
          sleep 20
          
          # Запускаем тесты
          ./gradlew test --info
          
          # Останавливаем сервер после тестов
          kill $SERVER_PID
